# Generated by Django 4.1.6 on 2023-03-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graphite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
