# Generated by Django 4.1.6 on 2023-02-10 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Graphite', '0004_profile_basic_calculator_profile_graphing_calculator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='left_students',
            field=models.ManyToManyField(blank=True, related_name='left_students', to='Graphite.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
